sudo: required

language: go

go_import_path: github.com/bosh-prometheus/bosh_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/bosh-exporter
  global:
    - secure: kuPmdO4Bn1zP0t4hh33OMPnxr1SeGezmi5mN1XBq5UWCnZUZOnKKMSyOz9X9KllCQKc+DSxNzWwsPfD3ycs8i2uxTypxqQ5UT5vKhRBpkp+4NopARrfxCf30LlEWIDKyvJbA+Omw6NPG9f7vRX8ydeMFtpVn1UuaZY96LO8Kx7qwosLdLimGTBw0BO8wvQcTJAGa4moUCbJ0J3s13ePSeGcYWQmQNpznsXWmhkDAzktb1064nvXN8eoFh0d+dW0wNlSJbLnWPCPKsRHO9uAsu/+MH3EIHwbBVv7irmYPJGD4bekapKvtqt2zQVqlAXClP/C3qZEBcPgx6m20wQkQzdOAt3iEW6cepSSBdZ/ZOZaxvvKIivM+cgXF2pjE8VsnzSSB7eA6XMKOSmyAGB+kYDbLKqXgeElUJS9fxOshH4yE1CNDrZImT4WLSYo/ZGHslbCQxrWJLg1zWLa3O0iZrB5PVx9TOOEthb+8kU80+xBTk9waO0OO9BNh5MJNsJR9U/waljSn8AqpyF9xgJpgR8ek84Ll+WnHePMbudC8miJKPPKEJjU+Cq/3cRHk667mzixf9coGg/fwgnoym61zWyJ+6a9w29adI1KFsjELfKvWnN0jbwqjo+CMg0umgCkfwFvAKcrvqaBGBliDGCU3IBarn9vygDO2mmXPtK2Jtq8=
    - secure: Lr8tWv7O3d9b/tVNX6+997Qtc5HJ3jP27CXygLnWncQZGLR8dVIH4WAgDxrodn8Ij17o5nTCqdERDTZVx2jcYaloImEQQ7MnkxmKsLU7aCW0SLwsFCIdZxn/70WlyKzksThXMVBcHLDQBpRWUt5IymNLczbbGoXhSc71ZAe580h9eDIIpsgjjZNiS13XQ34sM+YsYHyAUn8WbWzFkHdCaiaFqfOiPvnpZVXap9P592ZBzGbZdZoAeNfFZHO8PgGI3q137mrCfC1hA4Z2OwN4FrS0SxdUA+wq4tISii+8keHuqgX2qyf9PzQfMx7DWm2A42CUp5HlB6/ltO4KD4R6H3vzj8OkZ8YmDiiPQSQWMEYrThVmntCWxcaMpKcGab3W9okiLEgAFATrRnnhEmSsM/Z3aY8rHz/TWS2mSJYu0ZB0Uwj1PnVfV37joNdGR4YjZm81nolCJILwVREYRW+gDvwqP7SbzdgL3PQocQyyxPS7crxdKgOUwa6ZMGP1jKc16bWeMy8se93ayxUD9tYZRyvdp9WNIzTkXhezGK7aefZU5aQBDrkQq99eVeWs/8JA1nBd2S/4L/fdkyKq2DIyer5yd5uD4xYumMNjLseStZPkSvn4nIKOjotZiCJguu0UsZku4j0unP0LS++yxqr7hYGD+oKBqI+3EcsrhwbkBV8=
    - secure: Or2Mwf3pcnmxR+U2QBCsWgoytn5Im+SPYZ0z9PPL4JwZALg40YwL7d1sSv1FS2NXSMTmHXd8TC86dpBXUAQ2PTbghnLsVWs3+FPrgC5Lr6XRPhugN6n1vHxZlxvCnVgESh2BFifBFlTr6KA1H522h4LpdTrs+/tmOZp9RNa5BdoJnM1w8f/x+cBvV3ULZxDrnLUBZYI+o8T3ykDQeHDKk6V15SCJCYWpUg/3vvRFBeSTMZddTCNr6DngZedymjjuDpkRngg+AkzmCTgw5ACnJxulmbe6yP8eFdqSTHHN0iA8cgzqsi+j02WGlGb6nQEHcbJj0BRunbhCUJGUfsb468/WgEhmcLqF+bfy15AzU7VMprMSV7nmIveG5P9usHIEwWQUMpAGaZXUnY2HFPJ1rk0Y/khiMoIFGqmsGL+GV9iGkbwFViAs2CGcZTMJw2WMW/TeZ8g12WvqrdL4q/6NgwKAm/ULU2EniN1guHIOoWVCwfe4s4dNOBLkFwCnBxnBpprQuEtjhclb6tpdQYuOqTR31yv5Y8MmqQTUIc5DFnssSoWGSjj+dU4jIqEIvI76hOw15ym1l2BfqYW3W6ehDComVCiGZ17LOsYKaJPi0ZDLMCZ2m8CBwlEXtkNNg42AAKQUDAflKRITlSi/K3tW54meDyR0G7NXytIUamvRnC8=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_exporter bosh_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        - docker push $DOCKER_IMAGE_NAME
