name: Bump Go Version

on:
  schedule:
    - cron: '0 0 * * 1'  # weekly
  workflow_dispatch:

jobs:
  bump-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get current go toolchain version
        id: current-go-version
        uses: paketo-buildpacks/github-config/actions/update-go-mod-version@main
        with:
          go-version: ${{ steps.setup-go.outputs.go-version }}

      - name: Tidy dependencies
        run: go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump Go version to ${{ steps.latest-go.outputs.version }} + go mod tidy"
          title: "chore: bump Go version to ${{ steps.latest-go.outputs.version }}"
          branch: bump-go-version
          body: "Automated PR to bump Go version to `${{ steps.latest-go.outputs.version }}` + go mod tidy"
